
#################
# Game's routes
#################
index_game:
  path: /
  controller: App\Controller\GameController::index

create_game:
  path: /games
  methods: POST
  controller: App\Controller\GameController::new

put_stone_game:
  path: /games/{id}
  methods: POST
  controller: App\Controller\GameController::putStone


show_game:
  path: /games/{id}
  controller: App\Controller\GameController::show

#add_board:
#  path: /boards/{id}/stones
#  methods: POST
#  controller: App\Controller\StoneController::add

#################
# Board's routes
#################





